### ISSUE TITLE
A update for version 4, please!

### ISSUE THREAD

**Issue by fukhaos** [FokkeZB/Titanium-Docs#5]
A update for version 4.0, please!

**Comment by FokkeZB** [comment]
Blocked by https://jira.appcelerator.org/browse/TIDOC-2209

**Comment by yuchi** [comment]
Is this solved?

**Comment by FokkeZB** [comment]
Doesn't look like it: https://jira.appcelerator.org/browse/TIDOC-2209

**Comment by yuchi** [comment]
I asked since you released the app for the SDK 4.

**Comment by FokkeZB** [comment]
Oh, I did? :D Yes I see: https://github.com/FokkeZB/Titanium-Docs/releases

Well, they are now gone from builds.appcelerator.com in its entirety.

**Comment by yuchi** [comment]
Sooo… what about 5.0? :P

**Comment by FokkeZB** [comment]
Well, we need to wait for the linked TIDOC ticket :(

**Comment by yuchi** [comment]
:sob:

**Comment by bhatfield** [comment]
As a workaround, can you checkout https://github.com/appcelerator/appc-docs.git and switch to the gh-pages branch?

**Comment by FokkeZB** [comment]
@bhatfield thx, will do!
