### ISSUE TITLE
Find replacement for TideSDK

### ISSUE THREAD

**Issue by FokkeZB** [FokkeZB/Titanium-Docs#6]
Since TideSDK is dead, we need a different wrapper.

@ricardoalcocer what was it you were using for MDeck?

**Comment by yuchi** [comment]
Electronjs looks very promising, IMHO.

There's the lower level nwjs also.

**Comment by FokkeZB** [comment]
I've finished a Electronjs version but what I can't get working is copying the selected text via shortcut or context menu. Any idea how to do that?

**Comment by yuchi** [comment]
Horribly busy in these days. Gonna try to have a look later today.

**Comment by ricardoalcocer** [comment]
@FokkeZB , @yuchi , I used Tint2: https://www.trueinteractions.com/tint2/  Highly recommended.  Still in development, but I didn't find any problems to use it in production.

**Comment by yuchi** [comment]
@ricardoalcocer Tint2 looks good. I’d go with electron exclusively for the traction and eyeballs it has on itself.

**Comment by FokkeZB** [comment]
@ricardoalcocer I see that Tint2 comes as a Mac or Windows installer. That would make it hard to set this up via Jenkins. Or do you see ways in which it could.

Also, did you manage to make selected text in a Tint2 webview copy-able via a context menu or shortcut?
https://github.com/appcelerator-developer-relations/appc-docs-desktop/issues/3

**Comment by FokkeZB** [comment]
OK, fixed https://github.com/appcelerator-developer-relations/appc-docs-desktop/issues/3 so removing this repo in favour of https://github.com/appcelerator-developer-relations/appc-docs-desktop which I hope @bhatfield can automate nightly builds of to be uploaded to S3.
